### PR TITLE
Get Rows by Id for all tables

### PR DESCRIPTION
**Pull request by PauloN1**

### CODE REVIEW

**Comment by thaboRach** [comment]
@PauloN1 You just need to include the new Courses table.

**Review by aaronsh1 — COMMENTED** [review]
All good except change Qualifications to Courses.

**Review by thaboRach — APPROVED** [review]

**Review by aaronsh1 — COMMENTED** [review]
Add [dbo]. to stored procedure names.

**Review by aaronsh1 — COMMENTED** [review]
Add [dbo]. to stored proc names.

**Review by aaronsh1 — COMMENTED** [review]
Add [dbo]. to stored procedure names.

**Review by aaronsh1 — APPROVED** [review]

**Pull request merged**
